// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm.proto

package com.dc.lib.dto;

public final class CommProto {
  private CommProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 pageSize = 1;</code>
     * @return The pageSize.
     */
    int getPageSize();

    /**
     * <code>uint32 pageNum = 5;</code>
     * @return The pageNum.
     */
    int getPageNum();
  }
  /**
   * Protobuf type {@code PageInfo}
   */
  public static final class PageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PageInfo)
      PageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PageInfo.newBuilder() to construct.
    private PageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PageInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PageInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pageSize_ = input.readUInt32();
              break;
            }
            case 40: {

              pageNum_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dc.lib.dto.CommProto.internal_static_PageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dc.lib.dto.CommProto.internal_static_PageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dc.lib.dto.CommProto.PageInfo.class, com.dc.lib.dto.CommProto.PageInfo.Builder.class);
    }

    public static final int PAGESIZE_FIELD_NUMBER = 1;
    private int pageSize_;
    /**
     * <code>uint32 pageSize = 1;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }

    public static final int PAGENUM_FIELD_NUMBER = 5;
    private int pageNum_;
    /**
     * <code>uint32 pageNum = 5;</code>
     * @return The pageNum.
     */
    @java.lang.Override
    public int getPageNum() {
      return pageNum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageSize_ != 0) {
        output.writeUInt32(1, pageSize_);
      }
      if (pageNum_ != 0) {
        output.writeUInt32(5, pageNum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, pageSize_);
      }
      if (pageNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, pageNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dc.lib.dto.CommProto.PageInfo)) {
        return super.equals(obj);
      }
      com.dc.lib.dto.CommProto.PageInfo other = (com.dc.lib.dto.CommProto.PageInfo) obj;

      if (getPageSize()
          != other.getPageSize()) return false;
      if (getPageNum()
          != other.getPageNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + PAGENUM_FIELD_NUMBER;
      hash = (53 * hash) + getPageNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dc.lib.dto.CommProto.PageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dc.lib.dto.CommProto.PageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PageInfo)
        com.dc.lib.dto.CommProto.PageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dc.lib.dto.CommProto.internal_static_PageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dc.lib.dto.CommProto.internal_static_PageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dc.lib.dto.CommProto.PageInfo.class, com.dc.lib.dto.CommProto.PageInfo.Builder.class);
      }

      // Construct using com.dc.lib.dto.CommProto.PageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pageSize_ = 0;

        pageNum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dc.lib.dto.CommProto.internal_static_PageInfo_descriptor;
      }

      @java.lang.Override
      public com.dc.lib.dto.CommProto.PageInfo getDefaultInstanceForType() {
        return com.dc.lib.dto.CommProto.PageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.dc.lib.dto.CommProto.PageInfo build() {
        com.dc.lib.dto.CommProto.PageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dc.lib.dto.CommProto.PageInfo buildPartial() {
        com.dc.lib.dto.CommProto.PageInfo result = new com.dc.lib.dto.CommProto.PageInfo(this);
        result.pageSize_ = pageSize_;
        result.pageNum_ = pageNum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dc.lib.dto.CommProto.PageInfo) {
          return mergeFrom((com.dc.lib.dto.CommProto.PageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dc.lib.dto.CommProto.PageInfo other) {
        if (other == com.dc.lib.dto.CommProto.PageInfo.getDefaultInstance()) return this;
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getPageNum() != 0) {
          setPageNum(other.getPageNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dc.lib.dto.CommProto.PageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dc.lib.dto.CommProto.PageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>uint32 pageSize = 1;</code>
       * @return The pageSize.
       */
      @java.lang.Override
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>uint32 pageSize = 1;</code>
       * @param value The pageSize to set.
       * @return This builder for chaining.
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 pageSize = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int pageNum_ ;
      /**
       * <code>uint32 pageNum = 5;</code>
       * @return The pageNum.
       */
      @java.lang.Override
      public int getPageNum() {
        return pageNum_;
      }
      /**
       * <code>uint32 pageNum = 5;</code>
       * @param value The pageNum to set.
       * @return This builder for chaining.
       */
      public Builder setPageNum(int value) {
        
        pageNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 pageNum = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageNum() {
        
        pageNum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PageInfo)
    }

    // @@protoc_insertion_point(class_scope:PageInfo)
    private static final com.dc.lib.dto.CommProto.PageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dc.lib.dto.CommProto.PageInfo();
    }

    public static com.dc.lib.dto.CommProto.PageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageInfo>
        PARSER = new com.google.protobuf.AbstractParser<PageInfo>() {
      @java.lang.Override
      public PageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dc.lib.dto.CommProto.PageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncomm.proto\"-\n\010PageInfo\022\020\n\010pageSize\030\001 \001" +
      "(\r\022\017\n\007pageNum\030\005 \001(\rB\035\n\016com.dc.lib.dtoB\tC" +
      "ommProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageInfo_descriptor,
        new java.lang.String[] { "PageSize", "PageNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
